FROM golang:1.25-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
# Si client.go está en la raíz
RUN go build -o client client.go

FROM alpine:3.22
WORKDIR /root/
COPY --from=builder /app/client .
CMD ["./client"]