// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: tweet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductSaleService_ProcesarVenta_FullMethodName = "/blackfriday.ProductSaleService/ProcesarVenta"
)

// ProductSaleServiceClient is the client API for ProductSaleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductSaleServiceClient interface {
	ProcesarVenta(ctx context.Context, in *ProductSaleRequest, opts ...grpc.CallOption) (*ProductSaleResponse, error)
}

type productSaleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductSaleServiceClient(cc grpc.ClientConnInterface) ProductSaleServiceClient {
	return &productSaleServiceClient{cc}
}

func (c *productSaleServiceClient) ProcesarVenta(ctx context.Context, in *ProductSaleRequest, opts ...grpc.CallOption) (*ProductSaleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductSaleResponse)
	err := c.cc.Invoke(ctx, ProductSaleService_ProcesarVenta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductSaleServiceServer is the server API for ProductSaleService service.
// All implementations must embed UnimplementedProductSaleServiceServer
// for forward compatibility.
type ProductSaleServiceServer interface {
	ProcesarVenta(context.Context, *ProductSaleRequest) (*ProductSaleResponse, error)
	mustEmbedUnimplementedProductSaleServiceServer()
}

// UnimplementedProductSaleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductSaleServiceServer struct{}

func (UnimplementedProductSaleServiceServer) ProcesarVenta(context.Context, *ProductSaleRequest) (*ProductSaleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcesarVenta not implemented")
}
func (UnimplementedProductSaleServiceServer) mustEmbedUnimplementedProductSaleServiceServer() {}
func (UnimplementedProductSaleServiceServer) testEmbeddedByValue()                            {}

// UnsafeProductSaleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductSaleServiceServer will
// result in compilation errors.
type UnsafeProductSaleServiceServer interface {
	mustEmbedUnimplementedProductSaleServiceServer()
}

func RegisterProductSaleServiceServer(s grpc.ServiceRegistrar, srv ProductSaleServiceServer) {
	// If the following call panics, it indicates UnimplementedProductSaleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductSaleService_ServiceDesc, srv)
}

func _ProductSaleService_ProcesarVenta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductSaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductSaleServiceServer).ProcesarVenta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductSaleService_ProcesarVenta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductSaleServiceServer).ProcesarVenta(ctx, req.(*ProductSaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductSaleService_ServiceDesc is the grpc.ServiceDesc for ProductSaleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductSaleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blackfriday.ProductSaleService",
	HandlerType: (*ProductSaleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcesarVenta",
			Handler:    _ProductSaleService_ProcesarVenta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tweet.proto",
}
